[sim]
version = "5.1.0"
# add paths to additional extension folders
ext_folders = ["./sim/exts"]

[sim.ros]
enable_ros = true
isaacsim_ros_ws = "~/.pow/IsaacSim-ros_workspaces"
# support: humble, jazzy
ros_distro = "humble"

[[sim.profiles]]
name = "default"
cpu_performance_mode = false
headless = false
extensions = ["isaacsim.code_editor.vscode", "pow.camera.teleop_ros"]
raw_args = ["--/renderer/raytracingMotion/enabled=false"]
open_scene_path = ""

[[sim.profiles]]
name = "perf"
cpu_performance_mode = true
open_scene_path = "./sim/assets/ycb_test_scene_v2.usda"